//! Public read-only subscription export routes ("share links") for calendars
//! and addressbooks — Omnical extension (PLAN.md §17.7).
//!
//! The token in the URL is the only credential: this router mounts OUTSIDE
//! the DAV `AuthenticationLayer` and lookups happen by token alone (no
//! username is part of the request). Every failure — unknown token,
//! extension/kind mismatch, vanished (deleted) collection — answers 404,
//! never 401/403, so the public port offers neither an auth prompt nor a
//! token-validity oracle for scanners. GET/HEAD only (subscription polling
//! is client-driven); no write path exists by construction. ETags are
//! deliberately skipped.
//!
//! Payload parity: `.ics` is generated by the exact builder the
//! owner-authenticated CalDAV `route_get` export uses, and `.vcf` by the same
//! vCard concatenation the CardDAV `route_get` export uses — a token URL
//! serves byte-identical bytes to the owner export.

use axum::Router;
use axum::body::Body;
use axum::extract::{Path, State};
use axum::response::Response;
use axum::routing::get;
use headers::{ContentType, HeaderMapExt};
use http::StatusCode;
use rustical_caldav::calendar::methods::get::build_export_ics;
use rustical_store::{AddressbookStore, CalendarStore, Error, SubscriptionKind, SubscriptionStore};
use std::str::FromStr;
use std::sync::Arc;
use tracing::instrument;

struct ExportState<AS, CS> {
    addr_store: Arc<AS>,
    cal_store: Arc<CS>,
    sub_store: Arc<dyn SubscriptionStore>,
}

// Manual impl without `AS`/`CS` bounds: `Arc` is cloneable regardless of the
// pointee, which is all the router state needs.
impl<AS, CS> Clone for ExportState<AS, CS> {
    fn clone(&self) -> Self {
        Self {
            addr_store: Arc::clone(&self.addr_store),
            cal_store: Arc::clone(&self.cal_store),
            sub_store: Arc::clone(&self.sub_store),
        }
    }
}

/// Serve `GET/HEAD /export/{token}.ics` (calendars) and
/// `GET/HEAD /export/{token}.vcf` (addressbooks) without authentication.
///
/// The extension must match the subscription's collection kind; every failure
/// path (`Error::NotFound`) renders the same 404 as an unknown token, so the
/// different cases are indistinguishable from the outside.
#[instrument(skip(addr_store, cal_store, sub_store))]
async fn route_export<AS: AddressbookStore, CS: CalendarStore>(
    State(ExportState {
        addr_store,
        cal_store,
        sub_store,
    }): State<ExportState<AS, CS>>,
    Path(filename): Path<String>,
) -> Result<Response, Error> {
    // `<token>.<extension>`: the extension selects the payload kind
    let Some((token, extension)) = filename.rsplit_once('.') else {
        return Err(Error::NotFound);
    };

    // Unknown token → 404
    let subscription = sub_store.get_subscription_by_token(token).await?;

    let mut response = Response::builder().status(StatusCode::OK);
    let hdrs = response.headers_mut().unwrap();

    match (subscription.kind, extension) {
        (SubscriptionKind::Calendar, "ics") => {
            // Vanished (deleted) calendars 404: `show_deleted = false`
            // filters soft-deleted collections the same way the DAV tree does
            let calendar = cal_store
                .get_calendar(&subscription.principal, &subscription.collection_id, false)
                .await?;
            let objects = cal_store
                .get_objects(&subscription.principal, &subscription.collection_id)
                .await?;
            hdrs.typed_insert(ContentType::from_str("text/calendar; charset=utf-8").unwrap());
            Ok(response
                .body(Body::new(build_export_ics(&calendar, objects)))
                .unwrap())
        }
        (SubscriptionKind::Addressbook, "vcf") => {
            // Vanished (deleted) addressbooks 404
            addr_store
                .get_addressbook(&subscription.principal, &subscription.collection_id, false)
                .await?;
            let objects = addr_store
                .get_objects(&subscription.principal, &subscription.collection_id)
                .await?;
            // The same concatenation the CardDAV `route_get` export serves
            let vcf = objects
                .iter()
                .map(|(_, object)| object.get_vcf())
                .collect::<Vec<_>>()
                .join("\r\n");
            hdrs.typed_insert(ContentType::from_str("text/vcard; charset=utf-8").unwrap());
            Ok(response.body(Body::new(vcf)).unwrap())
        }
        // Extension/kind mismatch → 404, indistinguishable from an unknown
        // token
        _ => Err(Error::NotFound),
    }
}

/// Build the unauthenticated subscription-export router (Omnical "share
/// links"). It must be mounted OUTSIDE any `AuthenticationLayer` — the token
/// in the URL is the only credential — and only while `[subscriptions]
/// enabled = true` (the config gate arrives with the main-crate wiring).
#[must_use]
pub fn export_router<AS: AddressbookStore, CS: CalendarStore>(
    addr_store: Arc<AS>,
    cal_store: Arc<CS>,
    sub_store: Arc<dyn SubscriptionStore>,
) -> Router {
    Router::new()
        .route("/export/{filename}", get(route_export::<AS, CS>))
        .with_state(ExportState {
            addr_store,
            cal_store,
            sub_store,
        })
}
